### PR TITLE
Simplify CNC collision to fix motion planning failures when moving between `Grasp Left` and `Grasp Right`

### PR DESCRIPTION
**Pull request by Abishalini**
image

Working Video - 
https://github.com/PickNikRobotics/moveit_studio_ws/assets/17363793/0b80dd86-7bcd-46dd-a175-457f342f93d6

Also, enabled using all planners through a port. This Studio PR adds the port to `SetupMTCMoveToJointState` behavior - https://github.com/PickNikRobotics/moveit_studio/pull/4198

### CODE REVIEW

**Review by sea-bass — APPROVED** [review]
This is beautiful, and was very much needed.

My only comment is whether we need to sweep through other Objectives in this configuration and turn on parallel planning for `SetupMTCMoveToJointState`, but that can be done in a separate PR.

**Comment by Abishalini** [comment]
I can turn on parallel planning in another PR

**Review by sea-bass — APPROVED** [review]
Can you update the screenshot in this PR just for traceability?

**Comment by eholum** [comment]
> I can turn on parallel planning for all the objectives in another PR

I think we'll have to enable it for all of them at once, right? Otherwise we end up with objectives with missing ports?

**Comment by sea-bass** [comment]
> > I can turn on parallel planning for all the objectives in another PR
> 
> I think we'll have to enable it for all of them at once, right? Otherwise we end up with objectives with missing ports?

Not with this particular flag, because the utility function it calls actually has its own fallback to false (@sjahr was forward thinking about backward compatibility)

**Comment by eholum** [comment]
> Not with this particular flag, because the utility function it calls actually has its own fallback to false (@sjahr was forward thinking about backward compatibility)

Ah thank you. I have asked this exact same question twice now.

**Pull request merged**
