### PR TITLE
Mock Hardware Scene v2.5 Cleanup

### PR DESCRIPTION
**Pull request by eholum**
This PR,

* Moves the CNC machine back to give the robot slightly more clearance.
* Removes unused waypoints.

### CODE REVIEW

**Comment by eholum** [comment]
@nbbrooks can you give this a quick once over and tell me what you think?

Should be something like:

* `cd ~/moveit_studio/moveit_studio_ws`
* `git fetch`
* `git checkout minor-mock-hw-cleanup`
* `cd ~/moveit_studio`
* `./moveit_studio build`
* `./moveit_studio reset`
* `./moveit_studio -v run -c picknik_ur_mock_hw_config`

**Review by sea-bass — COMMENTED** [review]
I noticed no failures with these changes, but will let @nbbrooks be the final arbiter here.

**Comment by nbbrooks** [comment]
- Unfavorite "Looping Pick and place"
- I am failing to planning from Look at Machine to Grasp Left (the 2nd Move to Joint State that is run)

**Comment by eholum** [comment]
> Unfavorite "Looping Pick and place"

Did you reset the workspace? This is not an objective that is usually available in the mock hw configuration so you may have something stale in your config.

> I am failing to planning from Look at Machine to Grasp Left (the 2nd Move to Joint State that is run), every time I run it.

I wasn't getting that many failures but it did fail occasionally. I adjusted the pose to bias it towards the left waypoint. I think the orientation of the shoulder joint causes problems... 3 wpnp has been running for a few minutes now without issue.

**Comment by nbbrooks** [comment]
I did not reset my workspace, Abi called me out on that, it is gone now.

The latest version (hash 14d2792) is running well for 5 loops or so, which usually it has failed by now. LGTM.

**Review by nbbrooks — APPROVED** [review]

**Pull request merged**
