### PR TITLE
Update SetupMTCMoveAlongFrameAxis parameters

### PR DESCRIPTION
**Pull request by Abishalini**
Resolves https://github.com/PickNikRobotics/moveit_studio/issues/5808

Related PR - https://github.com/PickNikRobotics/moveit_studio/pull/5429

### CODE REVIEW

**Comment by sea-bass** [comment]
Seems like a 3.0 branch was already cut, so do we need to retarget that?

**Comment by Abishalini** [comment]
The failing integration test in CI is
```
1: [test_basic_ur5e_objectives-20] [ RUN      ] ObjectiveFixture.TestInterpolateToJointState
1: [objective_server_node_main-7] [1704400088.623]: root                      IDLE -> RUNNING
1: [objective_server_node_main-7] [1704400088.623]: RetrieveJointStateParameter IDLE -> RUNNING
[Processing: picknik_ur_studio_integration_testing]                   
1: [test_basic_ur5e_objectives-20] Failed to get action result from server: timed out waiting for result after 30.000000 seconds.
1: [test_basic_ur5e_objectives-20] /opt/overlay_ws/src/moveit_studio_robot_config/picknik_ur5e_configs/src/moveit_studio_ws/src/picknik_ur_studio_integration_testing/test/test_basic_ur5e_objectives.cpp:191: Failure
1: [test_basic_ur5e_objectives-20] Value of: sendDoObjectiveSequenceGoal(std::move(do_objective_goal), 30.0)
1: [test_basic_ur5e_objectives-20]   Actual: false
1: [test_basic_ur5e_objectives-20] Expected: true
1: [test_basic_ur5e_objectives-20] [  FAILED  ] ObjectiveFixture.TestInterpolateToJointState (30213 ms)
```

There was a change in Studio about setting behavior parameter overrides. I'll create another PR to fix this

**Review by sea-bass — DISMISSED** [review]

**Review by sea-bass — CHANGES_REQUESTED** [review]
@Abishalini there were a few missed changes I found in my testing, and have updated them. However, I also think this task now needs to inherit MTC controllers, as I got this warning during execution:

```
[move_group-1] [WARN] [1704497461.270757476] [moveit_task_constructor_visualization.execute_task_solution]: The trajectory of stage '0' from task '' does not have any controllers specified for trajectory execution. This might lead to unexpected controller selection.
```

**Comment by sea-bass** [comment]
> @Abishalini there were a few missed changes I found in my testing, and have updated them. However, I also think this task now needs to inherit MTC controllers, as I got this warning during execution:
> 
> ```
> [move_group-1] [WARN] [1704497461.270757476] [moveit_task_constructor_visualization.execute_task_solution]: The trajectory of stage '0' from task '' does not have any controllers specified for trajectory execution. This might lead to unexpected controller selection.
> ```

Actually, I think this change has to happen at the source code level. This may be OK as long as we also land a fix to moveit studio.

**Review by sea-bass — APPROVED** [review]

**Pull request merged**
